CREATE SCHEMA IF NOT EXISTS projind2564149 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS projind2564149.`user` (
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(191) NULL DEFAULT NULL,
  pass VARCHAR(191) NULL DEFAULT NULL,
  email VARCHAR(191) NULL DEFAULT NULL,
  isAdmin TINYINT(1) NULL DEFAULT '0',
  PRIMARY KEY (id),
  UNIQUE INDEX User_email_key (email)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS projind2564149.product (
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(191) NOT NULL,
  price DOUBLE NOT NULL,
  userId INT NOT NULL,
  PRIMARY KEY (id),
  INDEX Product_userId_fkey (userId),
  CONSTRAINT Product_userId_fkey FOREIGN KEY (userId) REFERENCES projind2564149.`user` (id) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS projind2564149.`order` (
  id INT NOT NULL AUTO_INCREMENT,
  quantity INT NOT NULL,
  productId INT NOT NULL,
  userId INT NOT NULL,
  PRIMARY KEY (id),
  UNIQUE INDEX Order_productId_key (productId),
  INDEX Order_userId_fkey (userId),
  CONSTRAINT Order_productId_fkey FOREIGN KEY (productId) REFERENCES projind2564149.product (id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT Order_userId_fkey FOREIGN KEY (userId) REFERENCES projind2564149.`user` (id) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;
